/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next"; import { ArticleShell } from "@/components/article-shell";
export const metadata:Metadata={title:"コンサルティング実務のExcel関数と参照設計"}; const sections=[{id:"flow",label:"参照フロー"},{id:"lookup",label:"検索・シナリオ"},{id:"aggregation",label:"集計・日付"},{id:"control",label:"制御・エラー"},{id:"build",label:"構築例"}];
export default function Page(){return <ArticleShell no="07" title="コンサルティング実務のExcel関数と参照設計" lead="関数を多用することが高度なモデルではありません。入力箇所を限定し、前提条件から計算、財務三表、出力へ追跡可能な参照を組むことが実務品質につながります。" sections={sections}>
<h2 id="flow">一方向の参照フローを設計する</h2><div className="formula">前提条件 → 売上高計画・費用計画 → 損益計算書<br/>損益計算書・前提条件 → 貸借対照表 → キャッシュ・フロー計算書<br/>財務三表 → 借入金計画・企業価値評価 → アウトプット</div><p>アウトプットから計算シートへ戻る参照を作らず、同じ前提を複数シートへ手入力しません。シート名は日本語、前提コードは一意、期間列は全シートで同じ位置にします。</p>
<h2 id="lookup">検索とシナリオ切替</h2><div className="data-scroll"><table className="data-table"><thead><tr><th>関数</th><th>実務用途</th><th>使用方針</th></tr></thead><tbody><tr><td>XLOOKUP</td><td>前提コード、勘定科目、年度の検索</td><td>完全一致を基本とする</td></tr><tr><td>INDEX / MATCH</td><td>行列の二次元検索</td><td>既存モデルとの互換性が必要な場合</td></tr><tr><td>CHOOSECOLS</td><td>選択シナリオ列の抽出</td><td>Microsoft 365環境で使用</td></tr><tr><td>XMATCH</td><td>年度列やシナリオ列の位置取得</td><td>列挿入に強い参照を作る</td></tr></tbody></table></div><div className="formula">=XLOOKUP($B12,前提条件!$B$10:$B$200,INDEX(前提条件!$C$10:$E$200,0,XMATCH(前提条件!$H$2,前提条件!$C$8:$E$8)),NA(),0)</div><p>検索失敗時にゼロを返すと前提漏れを発見できません。構築中は`NA()`を返し、エラーを可視化します。</p>
<h2 id="aggregation">集計と日付処理</h2><div className="data-scroll"><table className="data-table"><thead><tr><th>関数</th><th>例</th><th>用途</th></tr></thead><tbody><tr><td>SUMIFS</td><td>=SUMIFS(金額,勘定科目,$B12,日付,"&lt;="&amp;H$5)</td><td>補助元帳や取引一覧の集計</td></tr><tr><td>AVERAGEIFS</td><td>=AVERAGEIFS(単価,商品区分,$B8)</td><td>区分別平均単価</td></tr><tr><td>EOMONTH</td><td>=EOMONTH(G$5,1)</td><td>月末日を横展開</td></tr><tr><td>YEARFRAC</td><td>=YEARFRAC(実行日,期末日)</td><td>初年度の日割り・年換算</td></tr><tr><td>SUMPRODUCT</td><td>=SUMPRODUCT(数量範囲,単価範囲)</td><td>商品別売上高の合計</td></tr></tbody></table></div>
<h2 id="control">制御関数とモデルチェック</h2><div className="formula">=IF(予測開始日&lt;=H$5,予測式,実績値)<br/>=MAX(0,最低現金-返済前現金)<br/>=MIN(返済可能額,期首借入金+新規借入額)<br/>=IF(ABS(資産合計-負債純資産合計)&lt;0.1,"正常","要確認")</div><p>`OFFSET`と`INDIRECT`は参照先が追いにくく、再計算負荷も高いため、原則として`INDEX`やテーブル構造化参照で代替します。長い入れ子の`IF`は、補助行または前提表へ分解します。</p>
<h2 id="build">AssumptionsからOutputまでの構築例</h2><ol><li>前提条件シートB列に「販売数量成長率」「平均単価上昇率」「法人実効税率」などの一意コードを設定する。</li><li>C～E列に下振れ・基本・上振れ、H2にシナリオ選択リストを置く。</li><li>売上高計画でXLOOKUPにより有効前提を取得し、数量と単価を更新する。</li><li>損益計算書は売上高計画の完成行を参照し、売上原価・人件費・税金を計算する。</li><li>貸借対照表は損益計算書と回転日数、増減明細から期末残高を作る。</li><li>キャッシュ・フロー計算書で期末現金を算出し、貸借対照表へ戻す。</li><li>アウトプットは財務三表の完成行だけを参照し、独自計算を置かない。</li></ol><div className="formula">アウトプット!H10 = 損益計算書!H10<br/>アウトプット!H11 = 損益計算書!H31<br/>アウトプット!H12 = キャッシュ・フロー計算書!H25<br/>アウトプット!H13 = 貸借対照表!H75</div><div className="callout warning"><strong>色分けの標準例</strong><br/>手入力は青、同一シート内数式は黒、他シート参照は緑、外部ファイル参照は赤。案件チーム内で凡例を固定し、モデル冒頭に明記します。</div>
</ArticleShell>}
