import Link from "next/link";
import { lessons } from "@/data/site";

export default function Home(){return <>
  <section className="border-b border-[#d8e0e5]"><div className="container grid min-h-[520px] items-center gap-12 py-16 lg:grid-cols-[1.05fr_.95fr]">
    <div><div className="eyebrow">非上場企業M&A / 財務モデリング</div><h1 className="mt-4 text-4xl font-bold leading-[1.2] md:text-6xl">数字を並べる前に、<br/><span className="text-[#147d73]">モデルの因果</span>を設計する。</h1><p className="mt-6 max-w-2xl text-lg text-[#607080]">前提条件、損益計算書、貸借対照表、キャッシュ・フロー計算書をExcelで連動させ、将来計画と買収後の資金繰りを検証する実務講座です。</p><div className="mt-8 flex flex-wrap gap-3"><Link className="button" href="/model-design">第1章から学ぶ</Link><Link className="button secondary" href="/excel-functions">Excel関数を学ぶ</Link></div></div>
    <div className="border border-[#9aa8b1] bg-white shadow-[12px_12px_0_#e6ebea]"><div className="flex items-center justify-between bg-[#217346] px-4 py-2 text-sm font-bold text-white"><span>買収モデル_v08.xlsx</span><span>モデルチェック：正常</span></div><div className="data-scroll"><table className="data-table min-w-[520px]"><thead><tr><th>基本シナリオ</th><th>2026年度</th><th>2027年度</th><th>2028年度</th></tr></thead><tbody><tr><td>売上高</td><td className="number">1,240</td><td className="number">1,352</td><td className="number">1,474</td></tr><tr><td>営業利益</td><td className="number">161</td><td className="number">189</td><td className="number">221</td></tr><tr><td>営業利益率</td><td className="number">13.0%</td><td className="number">14.0%</td><td className="number">15.0%</td></tr><tr><td>有利子負債／営業利益</td><td className="number">3.2倍</td><td className="number">2.4倍</td><td className="number">1.7倍</td></tr><tr><td>株主価値</td><td colSpan={3} className="number font-bold text-[#217346]">1,630</td></tr></tbody></table></div><div className="grid grid-cols-3 border-t border-[#d8e0e5] text-center text-xs"><span className="p-3">入力</span><span className="border-x border-[#d8e0e5] p-3">計算</span><span className="p-3">出力</span></div></div>
  </div></section>
  <section className="container py-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">学習カリキュラム</div><h2 className="section-title mt-2">Excelモデルを順番に完成させる</h2></div><p className="max-w-lg text-sm text-[#607080]">各章のセル参照は、前提条件から計算、財務三表、出力へ一方向に流れる共通設計です。</p></div><div className="mt-8 border-t-2 border-[#102235]">{lessons.map(x=><Link key={x.slug} href={`/${x.slug}`} className="grid gap-3 border-b border-[#d8e0e5] py-6 transition hover:bg-[#f7f8f6] md:grid-cols-[70px_1fr_2fr_100px]"><strong className="font-mono text-[#147d73]">{x.no}</strong><strong>{x.title}</strong><span className="text-sm text-[#607080]">{x.summary}</span><span className="text-right text-xs">{x.level}・{x.time}</span></Link>)}</div></section>
  <section className="bg-[#102235] text-white"><div className="container grid gap-8 py-14 md:grid-cols-[1fr_auto] md:items-center"><div><div className="text-xs font-bold tracking-[.15em] text-[#77c7bc]">実務ツール</div><h2 className="mt-2 text-3xl font-bold">読むだけで終わらせない。</h2><p className="mt-3 text-white/65">売上高モデルと前提条件チェックリストを、その場で操作できます。</p></div><Link href="/tools" className="button green">ツールを開く</Link></div></section>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"WebSite",name:"M&A Modeling Lab",inLanguage:"ja",description:"非上場企業M&Aの財務モデリング実務講座"})}} />
  </>}
