import Link from "next/link";
import { CtaLink } from "@/components/CtaLink";
import { lessons } from "@/data/site";

export default function Home(){return <>
  <section className="border-b border-[#d8e0e5]"><div className="container grid min-h-[560px] items-center gap-12 py-16 lg:grid-cols-[1.08fr_.92fr]"><div><div className="eyebrow">FROM THEORY TO DEAL-READY MODEL</div><h1 className="mt-4 text-4xl font-bold leading-[1.18] md:text-6xl">読むだけで終わらない。<br/><span className="text-[#147d73]">実務で組める財務モデラー</span>へ。</h1><p className="mt-6 max-w-2xl text-lg text-[#607080]">各勘定科目の前提設計、財務三表の連動、Excelのセル接続まで。M&Aの現場で検証に耐える財務モデルを、自分の手で構築できるレベルへ引き上げます。</p><div className="mt-8 flex flex-wrap gap-3"><CtaLink className="button" href="/model-design" label="第1章から始める" location="home_hero">第1章から始める</CtaLink><CtaLink className="button secondary" href="/pl-model" label="勘定科目から学ぶ" location="home_hero">勘定科目から学ぶ</CtaLink></div></div><div className="border border-[#9aa8b1] bg-white shadow-[12px_12px_0_#e6ebea]"><div className="flex items-center justify-between bg-[#217346] px-4 py-2 text-sm font-bold text-white"><span>買収モデル_v08.xlsx</span><span>モデルチェック：正常</span></div><div className="data-scroll"><table className="data-table min-w-[520px]"><thead><tr><th>基本シナリオ</th><th>2026年度</th><th>2027年度</th><th>2028年度</th></tr></thead><tbody><tr><td>売上高</td><td className="number">1,240</td><td className="number">1,352</td><td className="number">1,474</td></tr><tr><td>営業利益</td><td className="number">161</td><td className="number">189</td><td className="number">221</td></tr><tr><td>営業利益率</td><td className="number">13.0%</td><td className="number">14.0%</td><td className="number">15.0%</td></tr><tr><td>有利子負債／営業利益</td><td className="number">3.2倍</td><td className="number">2.4倍</td><td className="number">1.7倍</td></tr><tr><td>株主価値</td><td colSpan={3} className="number font-bold text-[#217346]">1,630</td></tr></tbody></table></div><div className="grid grid-cols-3 border-t border-[#d8e0e5] text-center text-xs"><span className="p-3">入力</span><span className="border-x border-[#d8e0e5] p-3">計算</span><span className="p-3">出力</span></div></div></div></section>
  <section className="bg-[#f7f8f6]"><div className="container grid gap-10 py-16 lg:grid-cols-[.7fr_1.3fr]"><div><div className="eyebrow">WHY WE BUILT THIS</div><h2 className="section-title mt-2">「結局、セルをどうつなぐのか」が見つからなかった。</h2></div><div className="space-y-5 text-[1.02rem]"><p>これまでの書籍や財務モデル紹介サイトでも、モデル全体の設計思想や、PL・BS・CFという財務三表の回し方は学べます。しかし実務で必要になる、売掛金、棚卸資産、固定資産、のれん、繰延税金負債といった<strong>各勘定科目をどう設計するか</strong>、前提条件シートから計算シート、アウトプットへ<strong>Excelでどう接続するか</strong>まで詳しく解説したものは、ほとんどありませんでした。</p><p>作成者自身もM&A業務に従事する中で、理論は理解できても、実際のモデルへ落とす段階で何度も手が止まりました。レビューに耐える数式、循環参照を避ける順序、案件固有の前提の置き方は、断片的な情報と実務経験から自分で組み立てるしかなかったのです。</p><p className="border-l-4 border-[#217346] pl-5 font-semibold">その不便を次の担当者に残さないために、勘定科目からセル参照までを一つにつないだFinance Modeling Labを作りました。</p></div></div></section>
  <section className="container py-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">CURRICULUM</div><h2 className="section-title mt-2">実務モデルを順番に完成させる</h2></div><p className="max-w-lg text-sm text-[#607080]">前提条件から計算、財務三表、アウトプットへ、一方向に参照を流す順序で学びます。</p></div><div className="mt-8 border-t-2 border-[#102235]">{lessons.map(x=><Link key={x.slug} href={`/${x.slug}`} className="grid gap-3 border-b border-[#d8e0e5] py-6 transition hover:bg-[#f7f8f6] md:grid-cols-[70px_1fr_2fr_100px]"><strong className="font-mono text-[#147d73]">{x.no}</strong><strong>{x.title}</strong><span className="text-sm text-[#607080]">{x.summary}</span><span className="text-right text-xs">{x.level}・{x.time}</span></Link>)}</div></section>
  <section className="bg-[#102235] text-white"><div className="container grid gap-8 py-14 md:grid-cols-[1fr_auto] md:items-center"><div><div className="text-xs font-bold tracking-[.15em] text-[#77c7bc]">BUILD THIS LAB TOGETHER</div><h2 className="mt-2 text-3xl font-bold">次にほしい解説や機能を教えてください。</h2><p className="mt-3 max-w-2xl text-white/65">扱ってほしい勘定科目、Excelテンプレート、モデル機能などを自由にリクエストできます。</p></div><CtaLink href="/request" label="リクエストを送る" location="home_bottom" className="button green">リクエストを送る</CtaLink></div></section>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"WebSite",name:"Finance Modeling Lab",inLanguage:"ja",description:"財務モデリングを実務レベルで構築できる力を養う学習サイト"})}} />
  </>}
