import Link from "next/link";
import { lessons } from "@/data/site";

export default function Home(){return <>
  <section className="border-b border-[#d8e0e5]"><div className="container grid min-h-[520px] items-center gap-12 py-16 lg:grid-cols-[1.05fr_.95fr]">
    <div><div className="eyebrow">PRIVATE COMPANY M&A</div><h1 className="mt-4 text-4xl font-bold leading-[1.2] md:text-6xl">数字を並べる前に、<br/><span className="text-[#147d73]">モデルの因果</span>を設計する。</h1><p className="mt-6 max-w-2xl text-lg text-[#607080]">非上場企業のM&Aモデルを、前提条件、KPI、財務三表、買収後キャッシュフローまで段階的に組み立てる実務ガイドです。</p><div className="mt-8 flex flex-wrap gap-3"><Link className="button" href="/model-design">第1章から学ぶ</Link><Link className="button secondary" href="/tools">実務ツールを使う</Link></div></div>
    <div className="border border-[#9aa8b1] bg-white shadow-[12px_12px_0_#e6ebea]"><div className="flex items-center justify-between bg-[#217346] px-4 py-2 text-sm font-bold text-white"><span>Acquisition_Model_v08.xlsx</span><span>MODEL CHECK: OK</span></div><div className="data-scroll"><table className="data-table min-w-[520px]"><thead><tr><th>Operating Case</th><th>FY26</th><th>FY27</th><th>FY28</th></tr></thead><tbody><tr><td>Revenue</td><td className="number">1,240</td><td className="number">1,352</td><td className="number">1,474</td></tr><tr><td>EBITDA</td><td className="number">186</td><td className="number">216</td><td className="number">250</td></tr><tr><td>EBITDA margin</td><td className="number">15.0%</td><td className="number">16.0%</td><td className="number">17.0%</td></tr><tr><td>Net debt / EBITDA</td><td className="number">3.2x</td><td className="number">2.4x</td><td className="number">1.7x</td></tr><tr><td>Equity value</td><td colSpan={3} className="number font-bold text-[#217346]">1,630</td></tr></tbody></table></div><div className="grid grid-cols-3 border-t border-[#d8e0e5] text-center text-xs"><span className="p-3">INPUT</span><span className="border-x border-[#d8e0e5] p-3">CALC</span><span className="p-3">OUTPUT</span></div></div>
  </div></section>
  <section className="container py-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">CORE CURRICULUM</div><h2 className="section-title mt-2">5章で、モデルを完成させる</h2></div><p className="max-w-lg text-sm text-[#607080]">各章は独立して読めますが、初めて構築する場合は01から順に進めると、Excelの作業順序と一致します。</p></div><div className="mt-8 border-t-2 border-[#102235]">{lessons.map(x=><Link key={x.slug} href={`/${x.slug}`} className="grid gap-3 border-b border-[#d8e0e5] py-6 transition hover:bg-[#f7f8f6] md:grid-cols-[70px_1fr_2fr_100px]"><strong className="font-mono text-[#147d73]">{x.no}</strong><strong>{x.title}</strong><span className="text-sm text-[#607080]">{x.summary}</span><span className="text-right text-xs">{x.level} · {x.time}</span></Link>)}</div></section>
  <section className="bg-[#102235] text-white"><div className="container grid gap-8 py-14 md:grid-cols-[1fr_auto] md:items-center"><div><div className="text-xs font-bold tracking-[.15em] text-[#77c7bc]">PRACTICE TOOLS</div><h2 className="mt-2 text-3xl font-bold">読むだけで終わらせない。</h2><p className="mt-3 text-white/65">売上KPIモデルと前提条件チェックリストを、その場で操作できます。</p></div><Link href="/tools" className="button green">ツールを開く</Link></div></section>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"WebSite",name:"M&A Modeling Lab",inLanguage:"ja",description:"非上場企業M&Aの財務モデリング実務ガイド"})}} />
  </>}
