"use client";
import { FormEvent, useState } from "react";
import { event, trackCtaClick, trackOutboundClick } from "@/lib/analytics";

export function RequestForm(){
  const [category,setCategory]=useState("新しい解説ページ"); const [title,setTitle]=useState(""); const [detail,setDetail]=useState(""); const [level,setLevel]=useState("実務で使用中"); const [name,setName]=useState("");
  function submit(e:FormEvent){e.preventDefault();const issueTitle=`[リクエスト] ${title}`;const body=["## リクエスト内容",detail,"","## カテゴリ",category,"","## 利用者レベル",level,"","## お名前・ニックネーム",name||"匿名","","---","Finance Modeling Labのリクエストフォームから送信"].join("\n");const url=`https://github.com/arsenal23vm-netizen/ma-modeling-lab/issues/new?title=${encodeURIComponent(issueTitle)}&body=${encodeURIComponent(body)}`;trackCtaClick("リクエスト送信", "request_form");trackOutboundClick("GitHub Issue作成", url);event("contact_submit",{category,level,page_path:typeof window==="undefined"?"":window.location.pathname});window.open(url,"_blank","noopener,noreferrer")}
  return <form onSubmit={submit} className="border-t-4 border-[#217346] bg-white p-6 shadow-[8px_8px_0_#e6ebea] md:p-8"><div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-bold">カテゴリ<select value={category} onChange={e=>setCategory(e.target.value)} className="mt-2 w-full border border-[#9aa8b1] bg-white px-3 py-3 font-normal"><option>新しい解説ページ</option><option>Excelテンプレート・ツール</option><option>既存ページの改善</option><option>誤り・リンク切れの報告</option><option>その他</option></select></label><label className="text-sm font-bold">あなたのレベル<select value={level} onChange={e=>setLevel(e.target.value)} className="mt-2 w-full border border-[#9aa8b1] bg-white px-3 py-3 font-normal"><option>これから学びたい</option><option>学習中</option><option>実務で使用中</option><option>専門家・プロフェッショナル</option></select></label></div><label className="mt-5 block text-sm font-bold">リクエストのタイトル<span className="text-[#a96100]"> *</span><input required maxLength={100} value={title} onChange={e=>setTitle(e.target.value)} placeholder="例：借入金スケジュールの作り方を追加してほしい" className="mt-2 w-full border border-[#9aa8b1] px-4 py-3 font-normal"/></label><label className="mt-5 block text-sm font-bold">詳しい内容<span className="text-[#a96100]"> *</span><textarea required minLength={10} rows={7} value={detail} onChange={e=>setDetail(e.target.value)} placeholder="どのような場面で困っているか、どんな内容があると便利かを自由に記入してください。" className="mt-2 w-full resize-y border border-[#9aa8b1] px-4 py-3 font-normal"/></label><label className="mt-5 block text-sm font-bold">お名前・ニックネーム（任意）<input value={name} maxLength={50} onChange={e=>setName(e.target.value)} className="mt-2 w-full border border-[#9aa8b1] px-4 py-3 font-normal"/></label><div className="mt-6 border-t border-[#d8e0e5] pt-6"><button className="button green w-full md:w-auto" type="submit">内容を確認して送信する</button><p className="mt-3 text-xs text-[#607080]">送信ボタンを押すとGitHubの投稿確認画面が開きます。GitHubへのログイン後、「Submit new issue」を押すと送信が完了します。入力内容は公開されますので、機密情報や個人情報は記載しないでください。</p></div></form>
}
