import type { Metadata } from "next"; import { ArticleShell } from "@/components/article-shell";
import { createPageMetadata } from "@/lib/page-metadata";
export const metadata:Metadata=createPageMetadata("/roadmap", {title:"完成までの実務ロードマップ",description:"情報受領からドライバー、財務三表、取引、リターン、レビューまで、M&Aモデルを完成させる実務手順と完了条件を整理します。"}); const sections=[{id:"scope",label:"スコープ設定"},{id:"build",label:"構築手順"},{id:"review",label:"レビュー"},{id:"deliver",label:"意思決定資料"}];
export default function Page(){return <ArticleShell no="05" href="/roadmap" title="完成までの実務ロードマップ" lead="締切直前にモデルを作り直さないために、情報受領、構築、検証、意思決定の順序と成果物を明確にします。" sections={sections}>
  <h2 id="scope">最初の90分でスコープを固定する</h2><p>対象期間、月次・年次粒度、必要シナリオ、買収ストラクチャー、最終アウトプットを合意します。データ不足は空欄で放置せず、暫定前提と差替期限をIssue Logへ記録します。</p>
  <h2 id="build">推奨する構築順序</h2><div className="data-scroll"><table className="data-table"><thead><tr><th>工程</th><th>成果物</th><th>完了条件</th></tr></thead><tbody><tr><td>1. Historical</td><td>3期実績・KPI</td><td>試算表と一致</td></tr><tr><td>2. Drivers</td><td>売上・費用モデル</td><td>実績再現が可能</td></tr><tr><td>3. 3 Statements</td><td>PL・BS・CF</td><td>BS Check = 0</td></tr><tr><td>4. Transaction</td><td>S&U・PPA・Debt</td><td>資金使途が一致</td></tr><tr><td>5. Returns</td><td>IRR・MOIC・感応度</td><td>主要前提を切替可能</td></tr></tbody></table></div>
  <h2 id="review">レビューは3層に分ける</h2><ul><li>Mechanical review：リンク切れ、符号、期間、単位、チェック。</li><li>Commercial review：KPIの実現性、市場整合性、必要投資。</li><li>Deal review：価格、調達、コベナンツ、出口、Downside耐性。</li></ul><div className="callout warning"><strong>提出直前に避けること</strong><br/>新しい機能追加、列挿入、大規模な数式短縮は行わず、変更履歴と主要出力の差分確認に集中します。</div>
  <h2 id="deliver">数字を意思決定へ変換する</h2><p>投資委員会にはBaseの一点予測だけでなく、価値を左右する前提、損益分岐点、資金不足が起きる条件を示します。モデルの全出力を載せるのではなく、問いに答えるチャートと表を選びます。</p><div className="formula">Investment Case = Value Drivers + Key Risks + Mitigants + Decision Thresholds</div>
 </ArticleShell>}
