import type { Metadata } from "next"; import { ArticleShell } from "@/components/article-shell";
export const metadata:Metadata={title:"壊れにくいM&Aモデルの設計",description:"入力・計算・出力を分離するM&A財務モデルの基本設計を解説。"};
const sections=[{id:"purpose",label:"モデルの目的"},{id:"architecture",label:"基本構造"},{id:"rules",label:"Excel設計ルール"},{id:"checks",label:"モデルチェック"}];
export default function Page(){return <ArticleShell no="01" title="壊れにくいM&Aモデルの設計" lead="良いモデルは、計算が合うだけでは足りません。第三者が前提を見つけ、ロジックを追い、短時間で異常値を発見できることが重要です。" sections={sections}>
  <h2 id="purpose">モデルの目的を一文で定義する</h2><p>M&Aモデルの目的は「将来を正確に当てること」ではなく、限られた情報の下で、取引条件と事業前提が投資リターン・資金繰り・財務健全性へどう波及するかを比較可能にすることです。</p><div className="callout"><strong>最初に固定する3つの問い</strong><br/>いくらまでなら買えるか。借入を返済できるか。計画が下振れしたとき、どこで資金が不足するか。</div>
  <h2 id="architecture">入力・計算・出力を分離する</h2><div className="data-scroll"><table className="data-table"><thead><tr><th>レイヤー</th><th>役割</th><th>代表シート</th><th>原則</th></tr></thead><tbody><tr><td>Input</td><td>外部データと仮定</td><td>Assumptions / Historical</td><td>手入力セルを色で識別</td></tr><tr><td>Calculation</td><td>事業・会計・取引ロジック</td><td>Revenue / 3 Statements / Debt</td><td>数式内への定数埋込みを避ける</td></tr><tr><td>Output</td><td>意思決定指標</td><td>Dashboard / Returns</td><td>入力を置かない</td></tr></tbody></table></div><p>シートの並び順も、左から入力、計算、出力に統一します。レビュー担当者がファイルを開いた瞬間に、モデルの読み方を推測できる状態が理想です。</p>
  <h2 id="rules">Excel設計ルール</h2><ul><li>同じ前提は一度だけ入力し、すべて参照でつなぐ。</li><li>期間軸、単位、符号規則を全シートで統一する。</li><li>ハードコード、他シート参照、同一シート数式を色分けする。</li><li>複雑な一式より、意味のある中間計算を残す。</li><li>シート間リンクは一方向を基本とし、循環参照を局所化する。</li></ul><div className="formula">Enterprise Value = Equity Value + Net Debt + Other Adjustments</div>
  <h2 id="checks">モデルチェックを先に作る</h2><p>チェックは完成後の付録ではなく、設計の一部です。BS一致、CF増減一致、Sources & Uses一致、借入残高のマイナス、税率や利益率のレンジを常時監視します。</p><div className="data-scroll"><table className="data-table"><thead><tr><th>チェック</th><th>式</th><th>許容値</th></tr></thead><tbody><tr><td>BS Check</td><td>総資産 − 負債純資産</td><td>0</td></tr><tr><td>Cash Check</td><td>期首現金 + CF増減 − 期末現金</td><td>0</td></tr><tr><td>S&U Check</td><td>Sources − Uses</td><td>0</td></tr></tbody></table></div>
 </ArticleShell>}
